# Generated by Django 4.2.7 on 2024-12-20 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gap', '0043_cropgrowthstage_cropstagetype_and_more'),
        ('dcas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DCASRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_range', models.FloatField()),
                ('max_range', models.FloatField()),
                ('code', models.CharField(max_length=50)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dcas.dcasconfig')),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gap.crop')),
                ('crop_growth_stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gap.cropgrowthstage')),
                ('crop_stage_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gap.cropstagetype')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gap.attribute')),
            ],
            options={
                'verbose_name': 'Rule',
                'db_table': 'dcas_rule',
            },
        ),
    ]
