# Generated by Django 4.2.7 on 2025-01-12 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gap', '0044_farmregistrygroup_farmregistry'),
        ('dcas', '0002_dcasrule'),
    ]

    operations = [
        migrations.CreateModel(
            name='GDDMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gdd_threshold', models.FloatField()),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dcas.dcasconfig')),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gap.crop')),
                ('growth_stage_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gap.cropstagetype')),
            ],
            options={
                'verbose_name': 'GDD Matrix',
                'db_table': 'gdd_matrix',
                'unique_together': {('crop', 'growth_stage_type', 'config')},
            },
        ),
        migrations.CreateModel(
            name='GDDConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_temperature', models.FloatField()),
                ('cap_temperature', models.FloatField()),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dcas.dcasconfig')),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gap.crop')),
            ],
            options={
                'verbose_name': 'GDD Config',
                'db_table': 'gdd_config',
                'unique_together': {('crop', 'config')},
            },
        ),
    ]
