# Generated by Django 4.2.7 on 2025-01-13 12:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gap', '0044_farmregistrygroup_farmregistry'),
        ('dcas', '0002_dcasrule'),
    ]

    operations = [
        migrations.CreateModel(
            name='DCASRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now, help_text='The time when the request was created.')),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gap.country')),
            ],
            options={
                'verbose_name': 'Request',
                'db_table': 'dcas_request',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='DCASOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='The time when the file was delivered.', null=True)),
                ('status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Queued', 'Queued'), ('Running', 'Running'), ('Stopped', 'Stopped with error'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Invalidated', 'Invalidated')], default='Pending', help_text='The delivery status of the file.', max_length=255, null=True)),
                ('request', models.ForeignKey(help_text='The DCAS request associated with this output.', on_delete=django.db.models.deletion.CASCADE, related_name='output', to='dcas.dcasrequest')),
            ],
            options={
                'verbose_name': 'Output',
                'db_table': 'dcas_output',
                'ordering': ['-delivered_at'],
            },
        ),
        migrations.CreateModel(
            name='DCASErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_message', models.TextField(help_text='Details about why the farm could not be processed.')),
                ('logged_at', models.DateTimeField(default=django.utils.timezone.now, help_text='The time when the error was logged.')),
                ('farm_id', models.ForeignKey(help_text='The unique identifier of the farm that failed to process.', on_delete=django.db.models.deletion.CASCADE, to='gap.farm')),
                ('request', models.ForeignKey(help_text='The DCAS request associated with this error.', on_delete=django.db.models.deletion.CASCADE, related_name='error_logs', to='dcas.dcasrequest')),
            ],
            options={
                'verbose_name': 'Error Log',
                'db_table': 'dcas_error_log',
                'ordering': ['-logged_at'],
            },
        ),
    ]
