# Generated by Django 4.2.7 on 2025-01-12 21:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gap', '0044_farmregistrygroup_farmregistry'),
        ('dcas', '0002_dcasrule'),
    ]

    operations = [
        migrations.CreateModel(
            name='DCASRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now, help_text='The time when the request was created.')),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gap.country')),
            ],
            options={
                'verbose_name': 'CAS Request',
                'db_table': 'dcas_request',
                'ordering': ['-requested_at'],
            },
        ),
    ]
