# Generated by Django 4.2.7 on 2025-01-12 21:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dcas', '0003_dcas_request_update'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dcasrequest',
            options={'ordering': ['-requested_at'], 'verbose_name': 'DCAS Request'},
        ),
        migrations.CreateModel(
            name='DCASOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='The time when the file was delivered.', null=True)),
                ('status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Queued', 'Queued'), ('Running', 'Running'), ('Stopped', 'Stopped with error'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Invalidated', 'Invalidated')], default='Pending', help_text='The delivery status of the file.', max_length=255, null=True)),
                ('request', models.ForeignKey(help_text='The DCAS request associated with this output.', on_delete=django.db.models.deletion.CASCADE, related_name='output', to='dcas.dcasrequest')),
            ],
            options={
                'verbose_name': 'DCAS Output',
                'verbose_name_plural': 'DCAS Outputs',
                'db_table': 'dcas_output',
                'ordering': ['-delivered_at'],
            },
        ),
    ]
