# Generated by Django 4.2.7 on 2025-01-22 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcas', '0005_alter_gddmatrix_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='dcaserrorlog',
            name='error_type',
            field=models.CharField(choices=[('MISSING_MESSAGES', 'Missing Messages'), ('PROCESSING_FAILURE', 'Processing Failure'), ('OTHER', 'Other')], default='OTHER', help_text='The type of error encountered.', max_length=50),
        ),
    ]
