# Generated by Django 4.2.7 on 2025-01-29 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gap', '0045_preferences_dcas_config_and_more'),
        ('dcas', '0006_dcaserrorlog_error_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='dcasrequest',
            name='config',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='dcasrequest',
            name='progress_text',
            field=models.TextField(blank=True, help_text='Progress or note from the pipeline.', null=True),
        ),
        migrations.AddField(
            model_name='dcasrequest',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Queued', 'Queued'), ('Running', 'Running'), ('Stopped', 'Stopped with error'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Invalidated', 'Invalidated')], default='Pending', help_text='The status of the process.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dcasrequest',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gap.country'),
        ),
    ]
