# Generated by Django 4.2.7 on 2025-01-30 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dcas', '0007_dcasoutput_delivery_by_dcasoutput_path_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dcaserrorlog',
            old_name='farm_id',
            new_name='farm',
        ),
    ]
