# Generated by Django 4.2.7 on 2024-07-03 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gap', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetCDFProviderMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metadata', models.JSONField(default=dict)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gap.provider')),
            ],
        ),
        migrations.CreateModel(
            name='NetCDFProviderAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(blank=True, max_length=512, null=True)),
                ('variable_name', models.CharField(max_length=512)),
                ('other_definitions', models.JSONField(blank=True, default=dict, null=True)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gap.attribute')),
                ('observation_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gap.observationtype')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gap.provider')),
            ],
        ),
        migrations.CreateModel(
            name='NetCDFFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Filename with its path in the object storage (S3)', max_length=512)),
                ('start_date_time', models.DateTimeField()),
                ('end_date_time', models.DateTimeField()),
                ('dmrpp_path', models.CharField(blank=True, help_text='DMR++ path in the object storage (S3)', max_length=512, null=True)),
                ('local_path', models.CharField(blank=True, help_text='Relative path to the local file cache', max_length=512, null=True)),
                ('created_on', models.DateTimeField()),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gap.provider')),
            ],
        ),
    ]
