# Generated by Django 4.2.7 on 2024-06-27 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gap', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngestorSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingestor_type', models.CharField(choices=[('Tahmo', 'Tahmo')], default='Tahmo', max_length=512)),
                ('file', models.FileField(blank=True, null=True, upload_to='ingestors/')),
                ('status', models.CharField(choices=[('RUNNING', 'RUNNING'), ('SUCCESS', 'SUCCESS'), ('FAILED', 'FAILED')], default='RUNNING', max_length=512)),
                ('notes', models.TextField(blank=True, null=True)),
                ('run_at', models.DateTimeField(auto_now_add=True)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='measurement',
            name='unit',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
