# Generated by Django 4.2.7 on 2024-08-08 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gap', '0002_crop_farmcategory_farmrsvpstatus_village_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingestorsession',
            name='ingestor_type',
            field=models.CharField(choices=[('Tahmo', 'Tahmo'), ('Farm', 'Farm'), ('CBAM', 'CBAM')], default='Tahmo', max_length=512),
        ),
    ]
