# Generated by Django 4.2.7 on 2024-08-11 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gap', '0004_farmshorttermforecast_pest_alter_farm_crop_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='phone_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
