# Generated by Django 4.2.7 on 2024-08-11 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gap', '0005_farm_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasettype',
            name='variable_name',
            field=models.CharField(default='default', max_length=512),
            preserve_default=False,
        ),
    ]
