# Generated by Django 4.2.7 on 2024-08-13 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gap', '0006_datasettype_variable_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='farmshorttermforecastdata',
            options={'ordering': ['dataset_attribute', '-value_date']},
        ),
        migrations.RenameField(
            model_name='farmshorttermforecastdata',
            old_name='attribute',
            new_name='dataset_attribute',
        ),
    ]
