# Generated by Django 4.2.7 on 2024-08-14 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gap', '0007_alter_farmshorttermforecastdata_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RainfallClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, unique=True)),
                ('min_value', models.FloatField(blank=True, null=True)),
                ('max_value', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
