# Generated by Django 4.2.7 on 2024-08-22 05:30

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import gap.models.preferences


class Migration(migrations.Migration):

    dependencies = [
        ('gap', '0008_rainfallclassification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_of_interest', django.contrib.gis.db.models.fields.PolygonField(default=gap.models.preferences.area_of_interest_default, srid=4326)),
            ],
            options={
                'verbose_name_plural': 'preferences',
            },
        ),
    ]
