# Generated by Django 4.2.7 on 2024-08-22 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gap', '0009_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingestorsession',
            name='additional_config',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='ingestorsession',
            name='ingestor_type',
            field=models.CharField(choices=[('Tahmo', 'Tahmo'), ('Farm', 'Farm'), ('CBAM', 'CBAM'), ('Salient', 'Salient'), ('Tomorrow.io', 'Tomorrow.io')], default='Tahmo', max_length=512),
        ),
    ]
