# Generated by Django 4.2.7 on 2024-08-25 17:44

from django.db import migrations, models
import gap.models.preferences


class Migration(migrations.Migration):

    dependencies = [
        ('gap', '0010_ingestorsession_additional_config_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferences',
            name='crop_plan_config',
            field=models.JSONField(blank=True, default=gap.models.preferences.crop_plan_config_default),
        ),
    ]
