# Generated by Django 4.2.7 on 2024-08-25 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gap', '0011_preferences_crop_plan_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasourcefile',
            name='format',
            field=models.CharField(choices=[('NETCDF', 'NETCDF'), ('ZARR', 'ZARR'), ('ZIP_FILE', 'ZIP_FILE')], max_length=512),
        ),
    ]
