# Generated by Django 4.2.7 on 2024-08-27 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gap', '0011_preferences_crop_plan_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
