# Generated by Django 4.2.7 on 2024-08-29 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gap', '0012_attribute_is_active_alter_datasourcefile_format_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetattribute',
            name='ensembles',
            field=models.BooleanField(default=False, help_text='Flag indicating that the attribute is an array of 50 ensembles.'),
        ),
    ]
