# Generated by Django 4.2.7 on 2024-09-03 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gap', '0013_datasetattribute_ensembles'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferences',
            name='documentation_url',
            field=models.URLField(blank=True, default='https://kartoza.github.io/tomorrownow_gap/', null=True),
        ),
    ]
