# Generated by Django 4.2.7 on 2024-09-04 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gap', '0015_rename_requested_date_cropinsightrequest_requested_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasourcefile',
            name='is_latest',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='datasourcefile',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
