# Generated by Django 4.2.7 on 2024-09-09 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gap', '0016_datasourcefile_is_latest_datasourcefile_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferences',
            name='arable_api_url',
            field=models.CharField(blank=True, default='https://api.arable.cloud/api/v2', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='collectorsession',
            name='ingestor_type',
            field=models.CharField(choices=[('Tahmo', 'Tahmo'), ('Farm', 'Farm'), ('CBAM', 'CBAM'), ('Salient', 'Salient'), ('Tomorrow.io', 'Tomorrow.io'), ('Arable', 'Arable')], default='Tahmo', max_length=512),
        ),
        migrations.AlterField(
            model_name='ingestorsession',
            name='ingestor_type',
            field=models.CharField(choices=[('Tahmo', 'Tahmo'), ('Farm', 'Farm'), ('CBAM', 'CBAM'), ('Salient', 'Salient'), ('Tomorrow.io', 'Tomorrow.io'), ('Arable', 'Arable')], default='Tahmo', max_length=512),
        ),
    ]
