# Generated by Django 4.2.7 on 2024-09-06 12:29

import django.contrib.gis.db.models.fields
from django.db import migrations
import gap.models.preferences


class Migration(migrations.Migration):

    dependencies = [
        ('gap', '0016_datasourcefile_is_latest_datasourcefile_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferences',
            name='salient_area',
            field=django.contrib.gis.db.models.fields.PolygonField(default=gap.models.preferences.area_of_salient_default, help_text='Area that Salient collector will use to pull the data', srid=4326),
        ),
    ]
