# Generated by Django 4.2.7 on 2024-09-10 01:46

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gap', '0017_preferences_salient_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('description', models.TextField(blank=True, null=True)),
                ('unique_id', models.CharField(max_length=255, unique=True)),
                ('geometry', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('elevation', models.FloatField()),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
    ]
