# Generated by Django 4.2.7 on 2024-09-27 01:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gap', '0020_farmgroup_remove_cropinsightrequest_farms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmgroup',
            name='farms',
            field=models.ManyToManyField(blank=True, null=True, to='gap.farm'),
        ),
        migrations.AlterField(
            model_name='farmgroup',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
