# Generated by Django 4.2.7 on 2024-09-26 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gap', '0021_alter_farmgroup_farms_alter_farmgroup_users'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ObservationType',
            new_name='StationType',
        ),
        migrations.RenameField(
            model_name='station',
            old_name='observation_type',
            new_name='station_type',
        ),
    ]
