# Generated by Django 4.2.7 on 2024-09-26 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gap', '0021_rename_observationtype_stationtype_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collectorsession',
            options={'ordering': ['-run_at']},
        ),
        migrations.AlterModelOptions(
            name='ingestorsession',
            options={'ordering': ['-run_at']},
        ),
        migrations.AddField(
            model_name='preferences',
            name='tahmo_api_url',
            field=models.CharField(blank=True, default='https://datahub.tahmo.org', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='station',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collectorsession',
            name='ingestor_type',
            field=models.CharField(choices=[('Tahmo', 'Tahmo'), ('Farm', 'Farm'), ('CBAM', 'CBAM'), ('Salient', 'Salient'), ('Tomorrow.io', 'Tomorrow.io'), ('Arable', 'Arable'), ('Grid', 'Grid'), ('Tahmo API', 'Tahmo API')], default='Tahmo', max_length=512),
        ),
        migrations.AlterField(
            model_name='ingestorsession',
            name='ingestor_type',
            field=models.CharField(choices=[('Tahmo', 'Tahmo'), ('Farm', 'Farm'), ('CBAM', 'CBAM'), ('Salient', 'Salient'), ('Tomorrow.io', 'Tomorrow.io'), ('Arable', 'Arable'), ('Grid', 'Grid'), ('Tahmo API', 'Tahmo API')], default='Tahmo', max_length=512),
        ),
    ]
