# Generated by Django 4.2.7 on 2024-09-27 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gap', '0023_alter_collectorsession_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gap.farmcategory'),
        ),
        migrations.AlterField(
            model_name='farm',
            name='rsvp_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gap.farmrsvpstatus'),
        ),
    ]
