# Generated by Django 4.2.7 on 2024-09-27 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gap', '0023_alter_collectorsession_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmsuitableplantingwindowsignal',
            name='last_2_days',
            field=models.FloatField(blank=True, help_text='The rain accumulationSum for last 2 days.', null=True),
        ),
        migrations.AddField(
            model_name='farmsuitableplantingwindowsignal',
            name='last_4_days',
            field=models.FloatField(blank=True, help_text='The rain accumulationSum for last 4 days.', null=True),
        ),
        migrations.AddField(
            model_name='farmsuitableplantingwindowsignal',
            name='today_tomorrow',
            field=models.FloatField(blank=True, help_text='The rain accumulationSum for today and tomorrow.', null=True),
        ),
        migrations.AddField(
            model_name='farmsuitableplantingwindowsignal',
            name='too_wet_indicator',
            field=models.CharField(blank=True, help_text='Too wet indicator.', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='farmsuitableplantingwindowsignal',
            name='signal',
            field=models.CharField(help_text='GoNoGo signals.', max_length=512),
        ),
    ]
