# Generated by Django 4.2.7 on 2024-10-09 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gap', '0027_station_altitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferences',
            name='dask_threads_num',
            field=models.IntegerField(default=2, help_text='Number of threads for dask parallel computation, higher number will use more memory.'),
        ),
    ]
