# Generated by Django 4.2.7 on 2024-10-11 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gap', '0028_preferences_dask_threads_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSourceFileCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=512)),
                ('created_on', models.DateTimeField()),
                ('expired_on', models.DateTimeField(blank=True, null=True)),
                ('source_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gap.datasourcefile')),
            ],
        ),
        migrations.AddConstraint(
            model_name='datasourcefilecache',
            constraint=models.UniqueConstraint(fields=('source_file', 'hostname'), name='source_hostname'),
        ),
    ]
