# Generated by Django 4.2.7 on 2024-10-17 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gap', '0030_preferences_ingestor_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='station_history',
            field=models.ForeignKey(blank=True, help_text='Station history of the measurement.', null=True, on_delete=django.db.models.deletion.CASCADE, to='gap.stationhistory'),
        ),
    ]
