# Generated by Django 4.2.7 on 2024-10-24 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gap', '0032_preferences_api_log_batch_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmgroup',
            name='phone_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
