# Generated by Django 4.2.7 on 2024-10-25 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gap', '0033_farmgroup_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='pest',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pest',
            name='scientific_name',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='pest',
            name='taxonomic_rank',
            field=models.CharField(blank=True, choices=[('domain', 'domain'), ('kingdom', 'kingdom'), ('phylum', 'phylum'), ('division', 'division'), ('class', 'class'), ('order', 'order'), ('family', 'family'), ('genus', 'genus'), ('species', 'species')], max_length=512, null=True),
        ),
    ]
