# Generated by Django 4.2.7 on 2024-10-28 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gap', '0034_pest_link_pest_scientific_name_pest_taxonomic_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectorsession',
            name='ingestor_type',
            field=models.CharField(choices=[('Tahmo', 'Tahmo'), ('Farm', 'Farm'), ('CBAM', 'CBAM'), ('Salient', 'Salient'), ('Tomorrow.io', 'Tomorrow.io'), ('Arable', 'Arable'), ('Grid', 'Grid'), ('Tahmo API', 'Tahmo API'), ('Tio Forecast Collector', 'Tio Forecast Collector'), ('WindBorne Systems API', 'WindBorne Systems API'), ('Cabi Prise Excel', 'Cabi Prise Excel')], default='Tahmo', max_length=512),
        ),
        migrations.AlterField(
            model_name='ingestorsession',
            name='ingestor_type',
            field=models.CharField(choices=[('Tahmo', 'Tahmo'), ('Farm', 'Farm'), ('CBAM', 'CBAM'), ('Salient', 'Salient'), ('Tomorrow.io', 'Tomorrow.io'), ('Arable', 'Arable'), ('Grid', 'Grid'), ('Tahmo API', 'Tahmo API'), ('Tio Forecast Collector', 'Tio Forecast Collector'), ('WindBorne Systems API', 'WindBorne Systems API'), ('Cabi Prise Excel', 'Cabi Prise Excel')], default='Tahmo', max_length=512),
        ),
    ]
