# Generated by Django 4.2.7 on 2024-10-28 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gap', '0035_alter_collectorsession_ingestor_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pest',
            name='short_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
