# Generated by Django 4.2.7 on 2024-11-15 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gap', '0038_measurement_gap_measure_dataset_c4f74a_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferences',
            name='dask_threads_num_api',
            field=models.IntegerField(default=2, help_text='Number of threads for dask parallel computation in API, higher number will use more memory.'),
        ),
    ]
