# Generated by Django 4.2.7 on 2024-11-19 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gap', '0039_preferences_dask_threads_num_api'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasourcefilecache',
            name='size',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
