# Generated by Django 4.2.7 on 2025-01-04 13:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gap', '0043_cropgrowthstage_cropstagetype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmRegistryGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now, help_text='The time when the registry is ingested.')),
                ('is_latest', models.BooleanField(default=False)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gap.country')),
            ],
            options={
                'ordering': ['-date_time'],
            },
        ),
        migrations.CreateModel(
            name='FarmRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planting_date', models.DateField()),
                ('growth_stage_start_date', models.DateField(blank=True, help_text='Start date when the growth stage is updated.', null=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gap.crop')),
                ('crop_growth_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gap.cropgrowthstage')),
                ('crop_stage_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gap.cropstagetype')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gap.farm')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gap.farmregistrygroup')),
            ],
            options={
                'unique_together': {('group', 'farm', 'crop', 'crop_stage_type', 'planting_date')},
            },
        ),
    ]
