# Generated by Django 4.2.7 on 2025-01-28 18:43

from django.db import migrations, models
import gap.models.preferences


class Migration(migrations.Migration):

    dependencies = [
        ('gap', '0044_farmregistrygroup_farmregistry'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferences',
            name='dcas_config',
            field=models.JSONField(blank=True, default=gap.models.preferences.default_dcas_config, help_text='Config for DCAS module.', null=True),
        ),
        migrations.AddField(
            model_name='preferences',
            name='duckdb_threads_num',
            field=models.IntegerField(default=2, help_text='Number of threads for duckdb computation, higher number will use more memory and cpu.'),
        ),
        migrations.AlterField(
            model_name='collectorsession',
            name='ingestor_type',
            field=models.CharField(choices=[('Tahmo', 'Tahmo'), ('Farm', 'Farm'), ('CBAM', 'CBAM'), ('Salient', 'Salient'), ('Tomorrow.io', 'Tomorrow.io'), ('Arable', 'Arable'), ('Grid', 'Grid'), ('Tahmo API', 'Tahmo API'), ('Tio Forecast Collector', 'Tio Forecast Collector'), ('WindBorne Systems API', 'WindBorne Systems API'), ('Cabi Prise Excel', 'Cabi Prise Excel'), ('CBAM Bias Adjusted', 'CBAM Bias Adjusted'), ('DCAS Rules', 'DCAS Rules'), ('Farm Registry', 'Farm Registry')], default='Tahmo', max_length=512),
        ),
        migrations.AlterField(
            model_name='ingestorsession',
            name='ingestor_type',
            field=models.CharField(choices=[('Tahmo', 'Tahmo'), ('Farm', 'Farm'), ('CBAM', 'CBAM'), ('Salient', 'Salient'), ('Tomorrow.io', 'Tomorrow.io'), ('Arable', 'Arable'), ('Grid', 'Grid'), ('Tahmo API', 'Tahmo API'), ('Tio Forecast Collector', 'Tio Forecast Collector'), ('WindBorne Systems API', 'WindBorne Systems API'), ('Cabi Prise Excel', 'Cabi Prise Excel'), ('CBAM Bias Adjusted', 'CBAM Bias Adjusted'), ('DCAS Rules', 'DCAS Rules'), ('Farm Registry', 'Farm Registry')], default='Tahmo', max_length=512),
        ),
    ]
