# Generated by Django 4.2.7 on 2025-01-30 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gap', '0045_preferences_dcas_config_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasourcefile',
            name='format',
            field=models.CharField(choices=[('NETCDF', 'NETCDF'), ('ZARR', 'ZARR'), ('ZIP_FILE', 'ZIP_FILE'), ('PARQUET', 'PARQUET')], max_length=512),
        ),
    ]
