# Generated by Django 4.2.7 on 2025-02-04 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gap', '0046_alter_dataset_store_type_alter_datasourcefile_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferences',
            name='api_use_parquet',
            field=models.BooleanField(default=False, help_text='When set to True, API will use parquet reader instead of EAV.'),
        ),
    ]
