# Generated by Django 4.2.7 on 2024-08-14 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spw', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SPWOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(help_text='e.g: Plant NOW Tier 1a. Make sure the result this is coming from SPW R Model.', max_length=100, unique=True)),
                ('tier', models.CharField(help_text='Tier of spw output. e.g: 1a.', max_length=100)),
                ('is_plant_now', models.BooleanField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
