# Generated by Django 4.2.7 on 2024-10-24 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=512, unique=True)),
                ('name', models.CharField(max_length=512)),
                ('type', models.CharField(blank=True, max_length=512, null=True)),
                ('application', models.CharField(choices=[('PRISE', 'PRISE')], default='PRISE', max_length=512)),
                ('group', models.CharField(choices=[('Start of Season', 'Start of Season'), ('PRISE Time To Action 1 - Beginning of the month', 'PRISE Time To Action 1 - Beginning of the month'), ('PRISE Time To Action 2 - Second half of the month', 'PRISE Time To Action 2 - Second half of the month'), ('End of season', 'End of season')], default='Start of Season', max_length=512)),
                ('note', models.TextField(blank=True, help_text='Just a note about the template.', null=True)),
                ('template', models.TextField(help_text='Field for storing messages in translation. Include {{ context_key }} as a placeholder to be replaced with the appropriate context.')),
                ('template_en', models.TextField(help_text='Field for storing messages in translation. Include {{ context_key }} as a placeholder to be replaced with the appropriate context.', null=True)),
                ('template_sw', models.TextField(help_text='Field for storing messages in translation. Include {{ context_key }} as a placeholder to be replaced with the appropriate context.', null=True)),
            ],
            options={
                'ordering': ('code',),
            },
        ),
    ]
