# Generated by Django 4.2.7 on 2024-10-25 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messagetemplate',
            options={'ordering': ('code',), 'verbose_name': 'Template'},
        ),
    ]
