# Generated by Django 4.2.7 on 2024-10-24 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gap', '0033_dataset_observation_type_alter_dataset_time_step'),
        ('gap_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetTypeAPIConfig',
            fields=[
                ('type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='gap.datasettype')),
                ('max_daterange', models.IntegerField(default=-1, help_text='Maximum date range that API can fetch data.')),
            ],
        ),
    ]
