# Generated by Django 4.2.7 on 2024-10-25 08:32

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import gap_api.models.location


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gap_api', '0002_datasettypeapiconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('geometry', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('file', models.FileField(upload_to=gap_api.models.location.location_file_path)),
                ('file_type', models.CharField(choices=[('geojson', 'geojson'), ('shapefile', 'shapefile'), ('GEOPACKAGE', 'GEOPACKAGE')], default='geojson', max_length=100)),
                ('created_on', models.DateTimeField()),
                ('expired_on', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='user_locationname'),
        ),
    ]
