# Generated by Django 4.2.7 on 2024-12-15 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gap_api', '0005_userfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfile',
            name='size',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
