# Generated by Django 4.2.7 on 2024-10-24 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('message', '0001_initial'),
        ('gap', '0032_preferences_api_log_batch_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriseMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm_group', models.ForeignKey(blank=True, help_text='A default message if farm group is not specified.', null=True, on_delete=django.db.models.deletion.CASCADE, to='gap.farmgroup')),
                ('messages', models.ManyToManyField(blank=True, to='message.messagetemplate')),
                ('pest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gap.pest')),
            ],
            options={
                'db_table': 'prise_message',
                'ordering': ('pest__name',),
                'unique_together': {('pest', 'farm_group')},
            },
        ),
    ]
