# Generated by Django 4.2.7 on 2024-10-25 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gap', '0033_farmgroup_phone_number'),
        ('prise', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrisePest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable_name', models.CharField(help_text='Pest variable name that being used on CABI PRISE CSV.', max_length=256)),
                ('pest', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gap.pest')),
            ],
        ),
    ]
