# Generated by Django 4.2.7 on 2024-10-30 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prise', '0004_prisemessageschedule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prisemessageschedule',
            old_name='week_of_month',
            new_name='day_occurrence_in_month',
        ),
    ]
