# Generated by Django 4.2.7 on 2024-10-30 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prise', '0005_rename_week_of_month_prisemessageschedule_day_occurrence_in_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prisedata',
            name='data_type',
            field=models.CharField(choices=[('Near Real Time', 'Near Real Time'), ('Climatological', 'Climatological')], default='Near Real Time', max_length=512),
        ),
    ]
