# Generated by Django 4.2.7 on 2024-06-20 07:46

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('attribute_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('provider_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('station_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.TextField()),
                ('country_ISO_A3', models.TextField()),
                ('geometry', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('provider_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ground_observations.provider', to_field='provider_id')),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('value', models.FloatField()),
                ('attribute_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ground_observations.attribute', to_field='attribute_id')),
                ('station_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ground_observations.station', to_field='station_id')),
            ],
        ),
    ]
